// /api/_lib/insults.js — the shame pool
// 50 pre-written tombstone epitaphs. Random pick per kill.
// Tone: brutal but funny, no slurs, no targeted hate. Standard crypto roast.

export const INSULTS = [
  "Folded harder than origami in a hurricane",
  "Sold the bottom like a true champion",
  "Diamond hands made of jello",
  "Couldn't hold a position if it was glued to him",
  "RIP — died of paper cuts",
  "His hands were softer than a baby's skin",
  "Sold for a McDonald's value meal",
  "Threw it all away for gas money",
  "The market called his bluff",
  "Couldn't even wait for green candles",
  "His conviction lasted shorter than a TikTok",
  "Pajama-handed pajama trader",
  "Sold at the EXACT bottom (verified)",
  "His exit liquidity has now exited",
  "Got rugged by his own anxiety",
  "Saw a red candle and panicked",
  "Wanted off the rocket before launch",
  "Couldn't outlast a single dip",
  "His patience expired before his options did",
  "Sold for a haircut and a haircut",
  "Played the long game for 17 minutes",
  "Believed in nothing but the sell button",
  "Gave up before the protein kicked in",
  "Capitulated harder than a divorced dad",
  "Liquidated his own beliefs",
  "His hands turned to sand before the pump",
  "Convinced himself this was the top",
  "Sold for crypto twitter clout",
  "Took profit on his own ambitions",
  "Found a reason to sell in his horoscope",
  "Held for one whole afternoon",
  "His thesis: 'idk maybe it dumps'",
  "Sold to fund his anxiety meds",
  "Diamond hands? More like styrofoam",
  "Made a small fortune from a large one",
  "Forgot why he bought in the first place",
  "Gave the chart a confused look and bailed",
  "Couldn't HODL a single conviction",
  "The dip ate his lunch and his dinner",
  "His resolve dissolved in seconds",
  "Cashed out for a sandwich",
  "Welcomed to the shame wall — permanent resident",
  "Volunteered to be exit liquidity",
  "His hands were Wonder Bread soft",
  "Sold so fast the chain barely caught up",
  "Confidence shattered by a 2% wick",
  "Hands made of damp napkins",
  "Spent his conviction at the gas station",
  "Gave up faster than New Year's resolutions",
  "Bagholder graduated to jeet emeritus",
];

export function randomInsult() {
  return INSULTS[Math.floor(Math.random() * INSULTS.length)];
}
